import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.PHARMA_SUPABASE||{};const configured=cfg.url&&cfg.anonKey&&!cfg.url.includes('YOUR_PROJECT');
const authView=document.querySelector('#auth-view'),dashboard=document.querySelector('#dashboard'),loginStatus=document.querySelector('#login-status'),formStatus=document.querySelector('#form-status');
const setStatus=(el,msg)=>{el.textContent=msg;el.classList.add('show')};
if(!configured){setStatus(loginStatus,'Supabase is not configured yet. Add SUPABASE_URL and SUPABASE_ANON_KEY as GitHub Actions secrets, then redeploy.');document.querySelector('#login-form button').disabled=true}
const supabase=configured?createClient(cfg.url,cfg.anonKey):null;
async function refresh(){if(!supabase)return;const {data:{session}}=await supabase.auth.getSession();if(session){authView.hidden=true;dashboard.hidden=false;document.querySelector('#user-label').textContent=session.user.email;await loadSettings();await loadClients()}else{authView.hidden=false;dashboard.hidden=true}}
async function loadSettings(){const {data,error}=await supabase.from('site_settings').select('key,value');if(error)return;const settings=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));Object.entries(settings).forEach(([key,value])=>{const el=document.querySelector('#setting-'+key);if(el)el.value=value})}
async function loadClients(){const {data,error}=await supabase.from('client_showcase').select('*').order('sort_order').order('created_at',{ascending:false});const list=document.querySelector('#client-list');if(error){setStatus(formStatus,error.message);return}list.innerHTML=data.length?data.map(c=>`<div class="client-row"><img src="${c.logo_url||'assets/pharmaridge-mark-source.png'}" alt=""><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.story||'')}</small></div><button class="delete" data-delete="${c.id}">Remove</button></div>`).join(''):'<p>No client stories published yet.</p>';list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeClient(b.dataset.delete))}
async function removeClient(id){if(!confirm('Remove this client from the public showcase?'))return;await supabase.from('client_showcase').delete().eq('id',id);await loadClients()}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email:email.value,password:password.value});if(error)setStatus(loginStatus,error.message);else await refresh()});
document.querySelector('#logout').onclick=async()=>{await supabase?.auth.signOut();await refresh()};
document.querySelector('#settings-form').addEventListener('submit',async e=>{e.preventDefault();if(!supabase)return;const rows=[...new FormData(e.target)].map(([key,value])=>({key,value:String(value)}));const {error}=await supabase.from('site_settings').upsert(rows,{onConflict:'key'});if(error)setStatus(document.querySelector('#settings-status'),error.message);else setStatus(document.querySelector('#settings-status'),'Site details saved. The public website will update shortly.')});
document.querySelector('#content-form').addEventListener('submit',async e=>{e.preventDefault();const type=document.querySelector('#content-type').value,name=document.querySelector('#content-name').value.trim(),meta=document.querySelector('#content-meta').value.trim(),description=document.querySelector('#content-description').value.trim(),url=document.querySelector('#content-url').value.trim(),file=document.querySelector('#content-image').files[0];let image_url='';if(file){const path=`content-${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9.-]/g,'-')}`;const upload=await supabase.storage.from('site-media').upload(path,file,{contentType:file.type});if(upload.error){setStatus(document.querySelector('#content-status'),upload.error.message);return}image_url=supabase.storage.from('site-media').getPublicUrl(path).data.publicUrl}let row=type==='team_profiles'?{name,role:meta,bio:description,image_url}:type==='partners'?{name,category:meta,description,logo_url:image_url,website_url:url}:type==='site_ads'?{title:name,message:description,image_url,cta_label:meta,cta_url:url}:type==='video_library'?{title:name,category:meta,youtube_url:url,description}: {title:name,category:meta,google_url:url,description};const {error}=await supabase.from(type).insert(row);if(error)setStatus(document.querySelector('#content-status'),error.message);else{e.target.reset();setStatus(document.querySelector('#content-status'),'Published successfully.')}});
document.querySelector('#client-form').addEventListener('submit',async e=>{e.preventDefault();if(!supabase)return;const name=document.querySelector('#client-name').value.trim(),story=document.querySelector('#client-story').value.trim(),file=document.querySelector('#client-logo').files[0];let logo_url='';if(file){const safe=file.name.toLowerCase().replace(/[^a-z0-9.-]/g,'-');const path=`${crypto.randomUUID()}-${safe}`;const upload=await supabase.storage.from('client-logos').upload(path,file,{upsert:false,contentType:file.type});if(upload.error){setStatus(formStatus,upload.error.message);return}logo_url=supabase.storage.from('client-logos').getPublicUrl(path).data.publicUrl}const {error}=await supabase.from('client_showcase').insert({name,story,logo_url});if(error)setStatus(formStatus,error.message);else{e.target.reset();setStatus(formStatus,'Client published successfully.');await loadClients()}});
refresh();