const cfg=window.PHARMA_SUPABASE||{};
const authView=document.querySelector('#auth-view'),dashboard=document.querySelector('#dashboard'),loginStatus=document.querySelector('#login-status'),formStatus=document.querySelector('#form-status');
const configured=!!(cfg.url&&cfg.anonKey&&!cfg.url.includes('YOUR_PROJECT'));
let session=JSON.parse(localStorage.getItem('pharma_auth_session')||'null');
const status=(el,msg)=>{if(!el)return;el.textContent=msg;el.classList.add('show')};
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function rest(path,options={}){if(!session?.access_token)throw Error('Your session has expired. Please sign in again.');const response=await fetch(`${cfg.url}/rest/v1/${path}`,{...options,headers:{apikey:cfg.anonKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});if(response.status===401){logout();throw Error('Your session has expired. Please sign in again.')}const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok)throw Error(data?.message||data?.hint||data?.error_description||`Request failed (${response.status})`);return data}
async function upload(bucket,file){const path=`${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9.-]/g,'-')}`;const response=await fetch(`${cfg.url}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:cfg.anonKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok)throw Error(await response.text());return `${cfg.url}/storage/v1/object/public/${bucket}/${path}`}
function showDashboard(){authView.hidden=true;dashboard.hidden=false;document.querySelector('#logout').hidden=false;document.querySelector('#user-label').textContent=session?.user?.email||''}
function logout(){session=null;localStorage.removeItem('pharma_auth_session');authView.hidden=false;dashboard.hidden=true;document.querySelector('#logout').hidden=true}
async function loadSettings(){const rows=await rest('site_settings?select=key,value');for(const row of rows){const el=document.querySelector('#setting-'+row.key);if(el)el.value=row.value}}
async function loadClients(){const rows=await rest('client_showcase?select=*&order=created_at.desc');const list=document.querySelector('#client-list');list.innerHTML=rows.length?rows.map(c=>`<div class="client-row"><img src="${c.logo_url||'assets/pharmaridge-mark-source.png'}" alt=""><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.story)}</small></div><button class="edit-client" data-edit-client="${c.id}">Edit</button><button class="delete" data-delete-client="${c.id}">Remove</button></div>`).join(''):'<p>No client stories published yet.</p>';list.querySelectorAll('[data-delete-client]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this client?')){await rest(`client_showcase?id=eq.${b.dataset.deleteClient}`,{method:'DELETE'});await loadClients()}});list.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=async()=>{const c=(await rest(`client_showcase?id=eq.${b.dataset.editClient}`))[0];document.querySelector('#client-id').value=c.id;document.querySelector('#client-name').value=c.name;document.querySelector('#client-story').value=c.story||'';status(formStatus,'Editing this client. Submit to save changes.')})}
const tables=[['team_profiles','People'],['partners','Partners'],['site_ads','Ads'],['video_library','Videos'],['resource_library','Documents']];
async function loadContent(){const out=document.querySelector('#content-records');let all=[];for(const [table,label] of tables){const data=await rest(`${table}?select=*&order=created_at.desc`);data.forEach(row=>all.push({table,label,row}))}out.innerHTML=all.length?'<h3 style="font:600 15px Manrope;color:#073b2f;margin:25px 0 8px">All content</h3>'+all.map(x=>`<div class="admin-client-row"><span><b>${x.label}</b> · ${escapeHtml(x.row.name||x.row.title)}</span><span><button class="edit-content" data-table="${x.table}" data-id="${x.row.id}">Edit</button> <button class="delete-content" data-table="${x.table}" data-id="${x.row.id}">Delete</button></span></div>`).join(''):'<p>No additional content published yet.</p>';out.querySelectorAll('.delete-content').forEach(b=>b.onclick=async()=>{if(confirm('Delete this content?')){await rest(`${b.dataset.table}?id=eq.${b.dataset.id}`,{method:'DELETE'});await loadContent()}});out.querySelectorAll('.edit-content').forEach(b=>b.onclick=async()=>{const r=(await rest(`${b.dataset.table}?id=eq.${b.dataset.id}`))[0];document.querySelector('#content-type').value=b.dataset.table;document.querySelector('#content-id').value=r.id;document.querySelector('#content-name').value=r.name||r.title||'';document.querySelector('#content-meta').value=r.role||r.category||r.cta_label||'';document.querySelector('#content-description').value=r.bio||r.description||r.message||'';document.querySelector('#content-url').value=r.website_url||r.cta_url||r.youtube_url||r.google_url||'';status(document.querySelector('#content-status'),'Editing this record. Submit to save changes.')})}
async function boot(){if(!configured){status(loginStatus,'Supabase configuration is missing.');return}if(!session){authView.hidden=false;dashboard.hidden=true;return}try{showDashboard();await Promise.all([loadSettings(),loadClients(),loadContent()])}catch(e){status(formStatus,e.message)}}
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();if(!configured)return;const button=e.target.querySelector('button');button.disabled=true;button.textContent='Signing in…';try{const response=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value})});const result=await response.json();if(!response.ok)throw Error(result.error_description||result.msg||'Email or password is incorrect.');session=result;localStorage.setItem('pharma_auth_session',JSON.stringify(result));await boot();loginStatus.classList.remove('show')}catch(e){status(loginStatus,e.message)}finally{button.disabled=false;button.innerHTML='Sign in <span>↗</span>'}};
document.querySelector('#logout').onclick=logout;
document.querySelector('#settings-form').onsubmit=async e=>{e.preventDefault();try{const rows=[...new FormData(e.target)].map(([key,value])=>({key,value:String(value)}));await rest('site_settings?on_conflict=key',{method:'POST',body:JSON.stringify(rows)});status(document.querySelector('#settings-status'),'Site details saved.')}catch(err){status(document.querySelector('#settings-status'),err.message)}};
document.querySelector('#client-form').onsubmit=async e=>{e.preventDefault();try{const id=document.querySelector('#client-id').value,name=document.querySelector('#client-name').value.trim(),story=document.querySelector('#client-story').value.trim(),file=document.querySelector('#client-logo').files[0];let row={name,story};if(file)row.logo_url=await upload('client-logos',file);const url=id?`client_showcase?id=eq.${id}`:'client_showcase';await rest(url,{method:id?'PATCH':'POST',body:JSON.stringify(row)});e.target.reset();document.querySelector('#client-id').value='';status(formStatus,id?'Client updated.':'Client published.');await loadClients()}catch(err){status(formStatus,err.message)}};
document.querySelector('#content-form').onsubmit=async e=>{e.preventDefault();try{const type=document.querySelector('#content-type').value,id=document.querySelector('#content-id').value,name=document.querySelector('#content-name').value.trim(),meta=document.querySelector('#content-meta').value.trim(),description=document.querySelector('#content-description').value.trim(),url=document.querySelector('#content-url').value.trim(),file=document.querySelector('#content-image').files[0];let image_url=file?await upload('site-media',file):'';let row={};if(type==='team_profiles')row={name,role:meta,bio:description,...(image_url?{image_url}:{})};else if(type==='partners')row={name,category:meta,description,website_url:url,...(image_url?{logo_url:image_url}:{})};else if(type==='site_ads')row={title:name,message:description,cta_label:meta,cta_url:url,...(image_url?{image_url}:{})};else if(type==='video_library')row={title:name,category:meta,youtube_url:url,description};else row={title:name,category:meta,google_url:url,description};await rest(id?`${type}?id=eq.${id}`:type,{method:id?'PATCH':'POST',body:JSON.stringify(row)});e.target.reset();document.querySelector('#content-id').value='';status(document.querySelector('#content-status'),id?'Content updated.':'Content published.');await loadContent()}catch(err){status(document.querySelector('#content-status'),err.message)}};
boot();