const cfg=window.PHARMA_SUPABASE||{};
const ready=cfg.url&&cfg.anonKey&&!cfg.url.includes('YOUR_PROJECT');
const get=async path=>{const r=await fetch(`${cfg.url}/rest/v1/${path}`,{headers:{apikey:cfg.anonKey,Authorization:`Bearer ${cfg.anonKey}`}});if(!r.ok)throw Error(await r.text());return r.json()};
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=v=>{if(!v)return '';try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
async function loadPublicData(){if(!ready)return;try{
 const settings=Object.fromEntries((await get('site_settings?select=key,value')).map(x=>[x.key,x.value]));
 document.querySelectorAll('[data-contact-email]').forEach(x=>{x.textContent=settings.contact_email||x.textContent;x.href='mailto:'+(settings.contact_email||'')});document.querySelectorAll('[data-contact-href]').forEach(x=>{x.href='mailto:'+(settings.contact_email||'');x.textContent=settings.contact_email||x.textContent});document.querySelectorAll('[data-contact-phone]').forEach(x=>{x.textContent=settings.contact_phone||x.textContent;x.href='tel:'+(settings.contact_phone||'').replace(/[^+\d]/g,'')});document.querySelectorAll('[data-office]').forEach(x=>x.innerHTML=(settings.head_office||x.textContent).replace(/\|/g,'<br>'));document.querySelectorAll('[data-price="essential"]').forEach(x=>x.textContent=settings.essential_price||x.textContent);document.querySelectorAll('[data-price="partner"]').forEach(x=>x.textContent=settings.partner_price||x.textContent);const banner=document.querySelector('.topline-inner span:first-child');if(banner&&settings.announcement)banner.innerHTML='<i class="pulse-dot"></i> '+escapeHtml(settings.announcement);
 const clients=await get('client_showcase?select=name,story,logo_url&featured=eq.true&order=sort_order,created_at.desc');const ct=document.querySelector('#client-track');if(ct&&clients.length)ct.innerHTML=clients.map(c=>`<article class="client-card"><img src="${safeUrl(c.logo_url)||'assets/pharmaridge-mark-source.png'}" alt="${escapeHtml(c.name)} logo"><div><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.story||'Using PharmaRidge to run with clarity.')}</p></div></article>`).join('');
 const people=await get('team_profiles?select=name,role,bio,image_url&published=eq.true&order=sort_order');const pg=document.querySelector('#people-grid');if(pg&&people.length)pg.innerHTML=people.map(p=>`<article class="person-card"><img src="${safeUrl(p.image_url)||'assets/pharmaridge-mark-source.png'}" alt="${escapeHtml(p.name)}"><div><span class="card-kicker">${escapeHtml(p.role)}</span><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.bio)}</p></div></article>`).join('');
 const partners=await get('partners?select=name,category,description,logo_url,website_url&published=eq.true&order=sort_order');const par=document.querySelector('#partners-grid');if(par&&partners.length)par.innerHTML=partners.map(p=>`<a class="partner-card" href="${safeUrl(p.website_url)}" target="_blank" rel="noopener"><img src="${safeUrl(p.logo_url)||'assets/pharmaridge-mark-source.png'}" alt="${escapeHtml(p.name)}"><div><span>${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description)}</p></div></a>`).join('');
 const videos=await get('video_library?select=title,category,youtube_url,description&published=eq.true&order=sort_order');const vg=document.querySelector('#video-grid'),cats=document.querySelector('#media-categories');const idOf=u=>{try{const x=new URL(u);return x.hostname.includes('youtu.be')?x.pathname.slice(1):x.searchParams.get('v')||''}catch{return ''}};if(vg&&videos.length){const categories=['All',...new Set(videos.map(v=>v.category).filter(Boolean))];cats.innerHTML=categories.map((c,i)=>`<button class="media-filter ${i?'':'active'}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');const render=c=>vg.innerHTML=videos.filter(v=>c==='All'||v.category===c).map(v=>`<article class="video-card"><a class="video-frame" href="${safeUrl(v.youtube_url)}" target="_blank" rel="noopener"><img src="https://img.youtube.com/vi/${idOf(v.youtube_url)}/hqdefault.jpg" alt="${escapeHtml(v.title)}"><span>▶</span></a><span class="card-kicker">${escapeHtml(v.category)}</span><h3>${escapeHtml(v.title)}</h3><p>${escapeHtml(v.description)}</p></article>`).join('');render('All');cats.querySelectorAll('button').forEach(b=>b.onclick=()=>{cats.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.category)})}
 const docs=await get('resource_library?select=title,category,google_url,description&published=eq.true&order=sort_order');const rg=document.querySelector('#resource-grid');if(rg&&docs.length)rg.innerHTML=docs.map(d=>`<a class="resource-card" href="${safeUrl(d.google_url)}" target="_blank" rel="noopener"><span class="resource-icon">↗</span><div><span class="card-kicker">${escapeHtml(d.category)}</span><h3>${escapeHtml(d.title)}</h3><p>${escapeHtml(d.description||'Open document ↗')}</p></div></a>`).join('');
 const ads=await get('site_ads?select=title,message,image_url,cta_label,cta_url&published=eq.true&order=sort_order,created_at.desc&limit=1'),ad=ads[0],pop=document.querySelector('#ad-popover');if(ad&&pop&&!sessionStorage.getItem('pharma-ad-'+ad.title)){document.querySelector('#ad-title').textContent=ad.title;document.querySelector('#ad-message').textContent=ad.message;const img=document.querySelector('#ad-image');img.hidden=!ad.image_url;if(ad.image_url)img.src=safeUrl(ad.image_url);const cta=document.querySelector('#ad-cta');cta.hidden=!(ad.cta_label&&ad.cta_url);if(!cta.hidden){cta.textContent=ad.cta_label;cta.href=safeUrl(ad.cta_url)}setTimeout(()=>pop.hidden=false,1800);document.querySelector('.ad-close').onclick=()=>{pop.hidden=true;sessionStorage.setItem('pharma-ad-'+ad.title,'1')}}
}catch(error){console.warn('PharmaRidge public data sync failed',error)}}
loadPublicData();
